# Docker Compose override for external services
# Use this when you want to use external PostgreSQL, Redis, or Typesense
# Usage: docker compose -f docker-compose.yml -f docker-compose.external.yml up

version: '3.8'

services:
  # GameRequest Application with external services
  ggrequestz:
    depends_on: []  # Remove internal service dependencies
    environment:
      # Use external database (override these in your .env)
      POSTGRES_HOST: ${EXTERNAL_POSTGRES_HOST:-localhost}
      POSTGRES_PORT: ${EXTERNAL_POSTGRES_PORT:-5432}
      POSTGRES_DB: ${EXTERNAL_POSTGRES_DB:-ggrequestz}
      POSTGRES_USER: ${EXTERNAL_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${EXTERNAL_POSTGRES_PASSWORD}
      
      # Use external Redis (override these in your .env)
      REDIS_URL: ${EXTERNAL_REDIS_URL:-redis://localhost:6379}
      
      # Use external Typesense (override these in your .env)
      TYPESENSE_HOST: ${EXTERNAL_TYPESENSE_HOST:-localhost}
      TYPESENSE_PORT: ${EXTERNAL_TYPESENSE_PORT:-8108}
      TYPESENSE_PROTOCOL: ${EXTERNAL_TYPESENSE_PROTOCOL:-http}

# Do not include internal services when using external ones
# They can still be manually included with profiles if needed